version: '3.8'
services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/greekaway
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: greekaway
    ports:
      - '5432:5432'
    volumes:
      - ./data/db_pg:/var/lib/postgresql/data
